import { Story } from 'inkjs';
import { Assets } from './assets';

export const loadStory = (game) => {
	// load .json file generated by inklecate and create story object
	const json = game.cache.json.get(Assets.Story);
	const story = new Story(json);
	return story;
};